Algoritmo sin_titulo
	definir gen, matriz Como Caracter
	definir i, tam, n como entero
	definir dim, log como logico
	
	Escribir "Para comprobar si contiene el virus Z introduzca la secuencia genetica de la muestra"
	Escribir "El gen a comprobar debe contener 9, 16 o 1369 bases, de lo contrario no sera un gen a considerar"
	leer gen
	gen=minusculas(gen)
	dim=verdadero
	log=verdadero
	long(gen, dim)
	carac(gen, log)
	mientras log=falso o dim=falso hacer
		escribir " La muestra ingresada es incompatible con el virus. Reingrese la muestra"
		leer gen
		gen=minusculas(gen)
		dim=verdadero
		log=verdadero
		long(gen, dim)
		carac(gen, log)
	FinMientras
//	GEN="CCADDBACCDDDDBDBCCABBAABDBCDCADDABABCDCDDABBBCABBABBDCADCCDABDDACDBBBDBDCCDDCABCAAAACDCDCCACDCDDADAADDACBDBCCDDBCBCBBAAADDAADCAABBBCBCCBCBDBCCBBCBABADAACDBDBADCBBACDADAADABBDBDBDBDCCDDCABCCCCCADBBBBCCDACCBBBDBDAADDBCCBCCBCBDDDDCCBAAACDDBBCAABAADABBBCCCCDCCBBDCDABCDACBCBACDBCCDABDBDCDCADCCBBADDBDCCADCCDCCACCDCDBCDBBADBAADBBCAADDABCAADADAABAACCBABDADADADDBCABDCCBBAADDDCDDCBADBCACCAAADCCDDABDBACBCAAADDBADBDACDDBDCBDCCCDDCACBCCCACCCCBACBAAAAACBCBCDAADCAACBCABDDABCBCBACCADABBBABBBBBAACADDDDBABACADAAABDDDCCDCACAACACADADBABACBABDBBADCDBBDACDCAABCADDBDBDCAABDCDABDDADDCDDBCBCDADCDBBDACABCDAABBCBADDDBCBADCABACDCABBCBCBCBCADBABBDBCCCADCADDCBABBDDDBBCBCDABACDDDABCCDBACCBDBADADDDAAACBDCDCCAACBDDCDCBADACDDDDBDCBAACDADBBDBDBCCACADBAABBAADAADDDACDDCDBDDBBDAADDAACCCACDBBBBBDCDCDDDABBCBAAADACADDCDCDCBCDCACAAABCADBDBBDDACCBBDABDDBCADCCCADDCDBACBBBDAADDCDAAADBBCDADBDBCBDDCAABCCDCCDCABCAACADADAACADDBBDABAABACDACDCDBBDDCCBCBCAAACBDBDBBBDBDBBCADCBACDCCBDACBBACBCADCDBACCADCDBDCDBBACBBCDCAAAAABCCDDCDDBBCBABCBCAABDBCCACBABDCABAACBDBDBCCCCADBBCDCCCAABADBACDDBADCDCAADDDCBDDBDCDCCCCCCCDBCDDBACBBCDACDADCACBDBBCCCDCCBCBCDACBDDDACCCAADBDBBDADDCCDDDBCDABCCBACCCCCBAACCBCABAAABBCABBCACCCABCDACBCDBDACACDDCACBCBBCCADABCBBDDABADDAAABACCBDCDABCBBBBACCDABAACDCACCCBBCDDACCDBCBCBAACBBBBADBCBCDABAAAABADAAAACDACADACDBBCCABADDDCACDCAACCDABBDBDAABADDBDCCCACDADBDDDCBBCBDCADCBCDAABDDDDBBBBCDDCC"
//	GEN="CACBCACAC"
	//GEN="ADDDABBDD"	
	//	GEN="BCBBABBACBBBBCBB"
	//GEN="ACCDBBADDDCCBACABDCBDCBADBDACBBBBDAABBCCBAACCABDBDCDDABDBDADAAACBBBBCDDDCBBBDDCDABBDDABDBDBBACADCDAAADACDDDACCDCACDDABACDCCCAABDDCCACDADDBCBAACCDBCBCDDDCAACCBAADCBBBCDCBBACBDCCDDADBABCAABBACABDCAACCBDADDCAAACCDBDBBCDDDDDACBCDDADDDDCBADADBDCADDABBCDAACBCCDDDADDADADAACCACDCDDABCCCADABBACDACCAADDBCBCCDADBCCADAAABDDDAABBABCADDCCAADDCDDCDCACBADADACADDAADCBDBCDBDDACDCBCDCCABBDCBACDDACCCDADBCADCACAAABBBCADDDDBCBACDBDAAADDDACCDACBBBADACCCDCACCBACDADBCBBDADACABAACBCCADDCCCCACCCCADBCCDAADCAABBABAADDBDADDABABCCABBCDDACCADAAADBBCCDBADCADCBBDADACCDDBCAAABBBDCAAAACBAADBABBABACDDBBCBDCDCADABABBDADCBADAACDBCBDABADBCBADCACADAABCDDCABACDDBDCBCBDCAAACBDABBCACBACCCBACACDCADBDCDCDDCAACDBDCBACDBBDAABDBBCBAAADBABDBAACAAACDCDAAABABDDDBCACADCBBAADCCDABCCCBBCACCBAABDAADDDCDACDDDBCDCCBABDABACCDCDCDABAABCABBADADCBDDACDDCDDCDACDADADCACBCDABABDDCCDBCCDABACDBDAABDBDDDBADDBACABDCDDBACDDBBDDBBACBCCAACABBDADDBCAACCBCCDADDBCAADDADCCCBAAABABBBBBCABAACADBCBBABACCABCDAABADCCCCDCCADDDCCABBDDDAAADDADACBBBCBDAADACABABBAACCCADADDABDBCADDDCCDBBCCBCDCDBDDDDCACDACDBBBDDBADDACADDADDABCACDCBBADDABBBDCBBDCDAABADDDDDBCACCCCAAACBCBCDBACCCDACCCDBCBDCBADBCDDACCDBDBDBCAAACDDCBAABDBCAADCADDBABABDCBCBCBBBCACBCADDCAAAAAACBBACBBCCACBDCDDDDADCAAACBABDDBDADBAADCBABDDBCDBABDBAADDDBACBBBCCCDBDDBDDAADBBADADDDCBCACBABCDBBABAADABCABCDBACBBBCDBADADDBDCBDABBDDDCDDCCACDCBDCADABAABCDCAACCDDBADBDBCDACAAACBCADCCCBAC"
	//	GEN="ABAABBCBD"
	//	GEN="CDDACCACCACAAABC"
//	GEN="BCAADCCBABCCBABB"
	tam=Longitud(gen)
	
	
	si tam=9 entonces 
		n=3
	sino
		si tam=16 Entonces
			n=4
		sino 
			n=37
		finsi
	FinSi
	dimension matriz(n,n)
	
	ingresarbases(matriz, gen, n)
	
	comprobacion(matriz, n)
	
FinAlgoritmo

subproceso long(gen, dim por referencia)
	si longitud(gen)<>9 y longitud(gen)<>16 y longitud(gen)<>1369 Entonces
		dim=Falso
	sino dim=Verdadero
	FinSi
FinSubProceso

SubProceso carac(gen, log por referencia)
	definir i como entero
	para i=0 hasta longitud(gen)-1 Hacer
			si subcadena(gen,i,i)<>"a" y subcadena(gen,i,i)<>"b" y subcadena(gen,i,i)<>"c" y subcadena(gen,i,i)<>"d" Entonces
				log=falso
				i= longitud(gen)-1
			FinSi
	FinPara
FinSubProceso

subproceso ingresarbases(matriz, gen, n)
	definir i, j, C como entero
	C=0
	para i=0 hasta n-1 Hacer
		para j=0 hasta n-1 Hacer
			matriz(i,j)=subcadena(gen,C,C)
			C=C+1
			escribir sin saltar " [" matriz(i,j) "] "
		FinPara
		Escribir ""
	FinPara

FinSubProceso

subproceso comprobacion(matriz, n)
	definir i, j Como Entero
	definir aux1, aux2, auxa, auxb como caracter
	definir log1, log2 como logico
	log1=Verdadero
	log2=verdadero
//	aux1=matriz(0,0)
	aux2=matriz(0,0)
//	auxa=matriz(0,0)
	auxb=matriz(0,n-1)
	para i=0 hasta n-1 Hacer
		para j=0 hasta n-1 Hacer
			si i=j Entonces
				aux1=matriz(i,j)
				si aux1=aux2 entonces 
					log1=verdadero
					aux2=aux1
				sino log1=Falso
				finsi
			FinSi
			si i+j=n-1 Entonces
				auxa=matriz(i,j)
				si auxa=auxb entonces 
					log2=verdadero
					auxb=auxa
				sino log2=Falso
				finsi
			FinSi
		FinPara
	FinPara
	
	si log1=Verdadero y log2=verdadero Entonces
		Escribir "Gen Zombie, corre por tu vida"
	sino escribir "No te comera el dueño de la muestra. No todo esta perdido"
	FinSi
FinSubProceso

